services:
  pdns-slave:
    build: .
    restart: on-failure
    environment:
      PDNS_launch: "gsqlite3"
      PDNS_gsqlite3_database: "./etc/powerdns/backend/db.sqlite"
      PDNS_secondary: "yes"
      PDNS_primary: "no"
      PDNS_allow_axfr_ips: "10.0.20.1"
      PDNS_local_address: "0.0.0.0"
      PDNS_local_port: 53
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./backend:/etc/powerdns/backend